export enum PROFILE_ACTIONS {
  PROFILE = "@@WEEK/PROFILE",
  PROFILE_SUCCESS = "@@WEEK/PROFILE_SUCCESS",
  PROFILE_FAILURE = "@@WEEK/PROFILE_FAILURE"
}

export enum EDIT_PROFILE_ACTIONS {
  EDIT_PROFILE = "@@WEEK/EDIT_PROFILE",
  EDIT_PROFILE_SUCCESS = "@@WEEK/EDIT_PROFILE_SUCCESS",
  EDIT_PROFILE_FAILURE = "@@WEEK/EDIT_PROFILE_FAILURE"
}