export enum WEEK_ACTIONS {
  GET_WEEK = "@@WEEK/GET_WEEK",
  GET_WEEK_SUCCESS = "@@WEEK/GET_WEEK_SUCCESS",
  GET_WEEK_FAILURE = "@@WEEK/GET_WEEK_FAILURE"
}

export enum ROWS_ACTIONS {
  GET_ROWS = "@@ROWS/GET_ROWS",
  GET_ROWS_SUCCESS = "@@ROWS/GET_ROWS_SUCCESS",
  GET_ROWS_FAILURE = "@@ROWS/GET_ROWS_FAILURE"
}