export enum MEDICAL_CERTIFICATION_ACTIONS {
  MEDICAL_CERTIFICATION = "@@WEEK/MEDICAL_CERTIFICATION",
  MEDICAL_CERTIFICATION_SUCCESS = "@@WEEK/MEDICAL_CERTIFICATION_SUCCESS",
  MEDICAL_CERTIFICATION_FAILURE = "@@WEEK/MEDICAL_CERTIFICATION_FAILURE"
}

export enum CLEAR_STATE {
  CLEAR_STATE = "@@WEEK/CLEAR_STATE",
  CLEAR_STATE_SUCCESS = "@@WEEK/CLEAR_STATE_SUCCESS",
  CLEAR_STATE_FAILURE = "@@WEEK/CLEAR_STATE_FAILURE"
}
