export enum MEDICAL_CERTIFICATION_ACTIONS {
  MEDICAL_CERTIFICATION = "@@WEEK/MEDICAL_CERTIFICATION",
  MEDICAL_CERTIFICATION_SUCCESS = "@@WEEK/MEDICAL_CERTIFICATION_SUCCESS",
  MEDICAL_CERTIFICATION_FAILURE = "@@WEEK/MEDICAL_CERTIFICATION_FAILURE"
}
