export enum MEDICAL_CERTIFICATION_ADMIN_ACTIONS {
  MEDICAL_CERTIFICATION_ADMIN = "@@WEEK/MEDICAL_CERTIFICATION_ADMIN",
  MEDICAL_CERTIFICATION_ADMIN_SUCCESS = "@@WEEK/MEDICAL_CERTIFICATION_ADMIN_SUCCESS",
  MEDICAL_CERTIFICATION_ADMIN_FAILURE = "@@WEEK/MEDICAL_CERTIFICATION_ADMIN_FAILURE"
}

export enum REFILL_STATUSES {
  REFILL_STATUSES = "@@WEEK/REFILL_STATUSES",
  REFILL_STATUSES_SUCCESS = "@@WEEK/REFILL_STATUSES_SUCCESS",
  REFILL_STATUSES_FAILURE = "@@WEEK/REFILL_STATUSES_FAILURE"
}

export enum CLEAR_STATE {
  CLEAR_STATE = "@@WEEK/CLEAR_STATE",
  CLEAR_STATE_SUCCESS = "@@WEEK/CLEAR_STATE_SUCCESS",
  CLEAR_STATE_FAILURE = "@@WEEK/CLEAR_STATE_FAILURE"
}