export enum EDIT_PROFILE_ACTIONS {
  EDIT_PROFILE = "@@WEEK/EDIT_PROFILE",
  EDIT_PROFILE_SUCCESS = "@@WEEK/EDIT_PROFILE_SUCCESS",
  EDIT_PROFILE_FAILURE = "@@WEEK/EDIT_PROFILE_FAILURE"
}

export enum MOUNT_EDIT_PROFILE_ACTIONS {
  MOUNT_EDIT_PROFILE = "@@WEEK/MOUNT_EDIT_PROFILE",
  MOUNT_EDIT_PROFILE_SUCCESS = "@@WEEK/MOUNT_EDIT_PROFILE_SUCCESS",
  MOUNT_EDIT_PROFILE_FAILURE = "@@WEEK/MOUNT_EDIT_PROFILE_FAILURE"
}

export enum CLEAR_EDIT_PROFILE_ACTIONS {
  CLEAR_EDIT_PROFILE = "@@WEEK/CLEAR_EDIT_PROFILE",
  CLEAR_EDIT_PROFILE_SUCCESS = "@@WEEK/CLEAR_EDIT_PROFILE_SUCCESS",
  CLEAR_EDIT_PROFILE_FAILURE = "@@WEEK/CLEAR_EDIT_PROFILE_FAILURE"
}

